var MetaLayerCharts_xt = {
	LineChart: {
		height          : "200",
		width           : "900",
		chartType       : "Line",
		cdaPath         : "/public/plugin-samples/fusion-charts/Fusion Charts/LineChart.cda",
		cdaDataAccessId : "2",
		chartTitle      : "Sales Per year",
		xAxisName       : "Years",
		yAxisName       : "Sales",
		free            : "false",
		seriesColor: "007878;0A9B9B;29AAAA",
		bgColor 		: "ffffff",	
		borderColor		: "ffffff",	
	},
	
	PieChart2D: {
		height          : "200",
		width           : "500",
		chartType       : "Pie2D",
		cdaPath         : "/public/plugin-samples/fusion-charts/Fusion Charts/PieChart2D.cda",
		cdaDataAccessId : "2",
		chartTitle      : "Sales Per year",
		seriesColor: "007878;0A9B9B;29AAAA",
		xAxisName       : "Years",
		yAxisName       : "Sales",
		free            : "false",
		bgColor 		: "ffffff",	
		borderColor		: "ffffff",	
		pieRadius		: "70",
	},
	
	AngularGaugeChart: {
		cdaPath         : "/public/plugin-samples/fusion-charts/Fusion Charts/AngularGauge.cda",
		chartType		: "AngularGauge",
		height			: "200",
		width			: "400",
		free			: "false",
		cdaDataAccessId	: "1",
		rangeValueCdaId : "2",
		colorRange		: "e44a00;f8bd19;6baa01;6baa01",
		bgColor			: "ffffff",
		bgRatio			: "100",
		bgAlpha			: "100",
		gaugeFillMix	: "{color}",
		gaugeStartAngle	: "250",
		gaugeEndAngle	: "-70",
		gaugeOuterRadius: "95", 
		gaugeInnerRadius: "55%",
		gaugeBorderColor: "545A57",
		pivotRadius		: "5",
		showPivotBorder	: "0", 
		pivotFillColor	: "545A57", 
		pivotFillAlpha	: "100", 
		majorTMNumber	: "7",
		majorTMColor	: "000000",
		minorTMColor	: "545A57",
		baseFontColor	: "000000",
		baseFontSize	: "16",
		showLimits		: "0",
		toolTipBgColor	: "545A57",
		toolTipBorderColor:"262626",
		borderColor		: "ffffff",
	},
	
	RealTimeLineChart: {
		cdaPath: "/public/plugin-samples/fusion-charts/Fusion Charts/RealTimeLine.cda",
		cdaDataAccessId:"1",
		free:"false",
		chartType:"RealTimeLine",
		chartTitle:"Sales Per year",
		caption:"Sales Per Year",
		subcaption:"(Refreshes every second)",
		height:"300",
		width:"400",
		xAxisName:"Time",
		yAxisName:"Sales",
		labelDisplay:"rotate",
		labelStep:"1",
		bgColor 		: "ffffff",	
		borderColor		: "ffffff",	
	},
	
	RealTimeBarChart: {
		cdaPath: "/public/plugin-samples/fusion-charts/Fusion Charts/RealTimeLine.cda",
		cdaDataAccessId:"1",
		free:"false",
		chartType:"RealTimeLine",
		chartTitle:"Sales Per year",
		caption:"Sales Per Year",
		subcaption:"(Refreshes every second)",
		height:"300",
		width:"400",
		xAxisName:"Time",
		yAxisName:"Sales",
		labelDisplay:"rotate",
		labelStep:"1",
		bgColor 		: "ffffff",	
		borderColor		: "ffffff",	
	}
};